# Packaging/detection test on Fedora - mirrors install.sh's dnf branch.
FROM fedora:40

RUN dnf install -y tpm2-tools gcc pam-devel && dnf clean all

WORKDIR /src
COPY bin/lib.sh bin/lib.sh
COPY pam/pam_tpm_keyring_authtok.c pam/pam_tpm_keyring_authtok.c
COPY test/distro/test-packaging.sh test/distro/test-packaging.sh

CMD ["bash", "test/distro/test-packaging.sh"]
